2021-05-28 04:05:13,843 INFO    MainThread:28893 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 04:05:13,843 INFO    MainThread:28893 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 04:05:13,843 INFO    MainThread:28893 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_040513-1w75uxy1/logs/debug.log
2021-05-28 04:05:13,843 INFO    MainThread:28893 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_040513-1w75uxy1/logs/debug-internal.log
2021-05-28 04:05:13,843 INFO    MainThread:28893 [wandb_init.py:init():369] calling init triggers
2021-05-28 04:05:13,843 INFO    MainThread:28893 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 2, 'batch_size': 16, 'init_lr': 0.0006819446792878748}
2021-05-28 04:05:13,843 INFO    MainThread:28893 [wandb_init.py:init():418] starting backend
2021-05-28 04:05:13,843 INFO    MainThread:28893 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 04:05:13,853 INFO    MainThread:28893 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 04:05:13,859 INFO    MainThread:28893 [backend.py:ensure_launched():136] started backend process with pid: 28902
2021-05-28 04:05:13,871 INFO    MainThread:28893 [wandb_init.py:init():423] backend started and connected
2021-05-28 04:05:13,872 INFO    MainThread:28893 [wandb_init.py:init():465] updated telemetry
2021-05-28 04:05:13,872 INFO    MainThread:28893 [wandb_init.py:init():484] communicating current version
2021-05-28 04:05:15,094 INFO    MainThread:28893 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 04:05:15,094 INFO    MainThread:28893 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 04:05:15,312 INFO    MainThread:28893 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 04:05:15,346 INFO    MainThread:28893 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 04:05:15,347 INFO    MainThread:28893 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 04:05:15,347 INFO    MainThread:28893 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 04:05:15,352 INFO    MainThread:28893 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 04:05:15,352 INFO    MainThread:28893 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 04:08:40,903 INFO    MainThread:28893 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-28 04:08:40,903 INFO    MainThread:28893 [wandb_run.py:_restore():1507] restore
2021-05-28 04:08:42,909 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:08:43,172 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:08:43,385 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3416
}

2021-05-28 04:08:43,760 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1171
  total_bytes: 3832
}

2021-05-28 04:08:43,862 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1171
  total_bytes: 3832
}

2021-05-28 04:08:43,963 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3832
  total_bytes: 3832
}

2021-05-28 04:08:44,065 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3832
  total_bytes: 3832
}

2021-05-28 04:08:44,166 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3832
  total_bytes: 3832
}

2021-05-28 04:08:44,267 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3832
  total_bytes: 3832
}

2021-05-28 04:08:44,369 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3832
  total_bytes: 3832
}

2021-05-28 04:08:44,470 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3832
  total_bytes: 3832
}

2021-05-28 04:08:44,572 INFO    MainThread:28893 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3832
  total_bytes: 3832
}

2021-05-28 04:08:45,651 INFO    MainThread:28893 [wandb_run.py:_show_files():1879] logging synced files
