2021-05-28 04:52:10,278 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 04:52:10,278 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 04:52:10,278 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_045210-3q0ojjik/logs/debug.log
2021-05-28 04:52:10,278 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_045210-3q0ojjik/logs/debug-internal.log
2021-05-28 04:52:10,278 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 04:52:10,278 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 288, 'batch_size': 8, 'init_lr': 0.002023075716417512}
2021-05-28 04:52:10,279 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 3tgrtbva
2021-05-28 04:52:10,279 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/3tgrtbva
2021-05-28 04:52:10,279 INFO    MainThread:29752 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-28 04:52:10,280 INFO    MainThread:29752 [wandb_run.py:_restore():1507] restore
2021-05-28 04:52:12,287 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:52:12,579 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:52:13,391 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3416
}

2021-05-28 04:52:13,807 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1385
  total_bytes: 4046
}

2021-05-28 04:52:13,909 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1385
  total_bytes: 4046
}

2021-05-28 04:52:14,010 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4046
  total_bytes: 4046
}

2021-05-28 04:52:14,112 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4046
  total_bytes: 4046
}

2021-05-28 04:52:14,213 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4046
  total_bytes: 4046
}

2021-05-28 04:52:14,315 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4046
  total_bytes: 4046
}

2021-05-28 04:52:14,416 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4046
  total_bytes: 4046
}

2021-05-28 04:52:14,518 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4046
  total_bytes: 4046
}

2021-05-28 04:52:14,620 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4046
  total_bytes: 4046
}

2021-05-28 04:52:15,701 INFO    MainThread:29752 [wandb_run.py:_show_summary():1812] rendering summary
2021-05-28 04:52:15,701 INFO    MainThread:29752 [wandb_run.py:_show_history():1850] rendering history
2021-05-28 04:52:15,703 INFO    MainThread:29752 [wandb_run.py:_show_files():1879] logging synced files
2021-05-28 04:52:15,706 INFO    MainThread:29752 [wandb_init.py:init():418] starting backend
2021-05-28 04:52:15,706 INFO    MainThread:29752 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 04:52:15,708 INFO    MainThread:29752 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 04:52:15,749 INFO    MainThread:29752 [backend.py:ensure_launched():136] started backend process with pid: 30002
2021-05-28 04:52:15,751 INFO    MainThread:29752 [wandb_init.py:init():423] backend started and connected
2021-05-28 04:52:15,753 INFO    MainThread:29752 [wandb_init.py:init():465] updated telemetry
2021-05-28 04:52:15,753 INFO    MainThread:29752 [wandb_init.py:init():484] communicating current version
2021-05-28 04:52:16,966 INFO    MainThread:29752 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 04:52:16,966 INFO    MainThread:29752 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 04:52:17,176 INFO    MainThread:29752 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 04:52:17,211 INFO    MainThread:29752 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 04:52:17,213 INFO    MainThread:29752 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 04:52:17,213 INFO    MainThread:29752 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 04:52:17,214 INFO    MainThread:29752 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 04:52:17,214 INFO    MainThread:29752 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 05:05:56,902 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 05:05:56,902 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 05:05:56,902 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_050556-sw3ialnt/logs/debug.log
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_050556-sw3ialnt/logs/debug-internal.log
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 384, 'batch_size': 16, 'init_lr': 0.00043564753541279065}
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 3q0ojjik
2021-05-28 05:05:56,903 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/3q0ojjik
