2021-05-28 04:04:52,145 INFO    MainThread:28850 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 04:04:52,145 INFO    MainThread:28850 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 04:04:52,145 INFO    MainThread:28850 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_040452-2fyqgnkh/logs/debug.log
2021-05-28 04:04:52,146 INFO    MainThread:28850 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_040452-2fyqgnkh/logs/debug-internal.log
2021-05-28 04:04:52,146 INFO    MainThread:28850 [wandb_init.py:init():369] calling init triggers
2021-05-28 04:04:52,146 INFO    MainThread:28850 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 5, 'batch_size': 32, 'init_lr': 0.0014617565700552008}
2021-05-28 04:04:52,146 INFO    MainThread:28850 [wandb_init.py:init():418] starting backend
2021-05-28 04:04:52,146 INFO    MainThread:28850 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 04:04:52,155 INFO    MainThread:28850 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 04:04:52,162 INFO    MainThread:28850 [backend.py:ensure_launched():136] started backend process with pid: 28859
2021-05-28 04:04:52,163 INFO    MainThread:28850 [wandb_init.py:init():423] backend started and connected
2021-05-28 04:04:52,164 INFO    MainThread:28850 [wandb_init.py:init():465] updated telemetry
2021-05-28 04:04:52,165 INFO    MainThread:28850 [wandb_init.py:init():484] communicating current version
2021-05-28 04:04:52,932 INFO    MainThread:28850 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 04:04:52,932 INFO    MainThread:28850 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 04:04:53,147 INFO    MainThread:28850 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 04:04:53,191 INFO    MainThread:28850 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 04:04:53,191 INFO    MainThread:28850 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 04:04:53,192 INFO    MainThread:28850 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 04:04:53,194 INFO    MainThread:28850 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 04:04:53,194 INFO    MainThread:28850 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 04:04:53,198 INFO    MainThread:28850 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-28 04:04:53,198 INFO    MainThread:28850 [wandb_run.py:_restore():1507] restore
2021-05-28 04:04:55,206 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:04:55,501 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:04:56,159 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3847
}

2021-05-28 04:04:56,549 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3435
  total_bytes: 3849
}

2021-05-28 04:04:56,651 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3435
  total_bytes: 3849
}

2021-05-28 04:04:56,754 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3849
  total_bytes: 3849
}

2021-05-28 04:04:56,855 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3849
  total_bytes: 3849
}

2021-05-28 04:04:56,957 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3849
  total_bytes: 3849
}

2021-05-28 04:04:57,059 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3849
  total_bytes: 3849
}

2021-05-28 04:04:57,161 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3849
  total_bytes: 3849
}

2021-05-28 04:04:57,263 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3849
  total_bytes: 3849
}

2021-05-28 04:04:57,365 INFO    MainThread:28850 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3849
  total_bytes: 3849
}

2021-05-28 04:04:58,457 INFO    MainThread:28850 [wandb_run.py:_show_files():1879] logging synced files
