2021-05-28 06:48:55,393 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 06:48:55,394 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 06:48:55,394 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_064855-2iv7ryy0/logs/debug.log
2021-05-28 06:48:55,394 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_064855-2iv7ryy0/logs/debug-internal.log
2021-05-28 06:48:55,394 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 06:48:55,394 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 224, 'batch_size': 64, 'init_lr': 0.00013190828627400773}
2021-05-28 06:48:55,394 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 2ox22mfs
2021-05-28 06:48:55,394 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/2ox22mfs
2021-05-28 06:48:55,394 INFO    MainThread:29752 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-28 06:48:55,395 INFO    MainThread:29752 [wandb_run.py:_restore():1507] restore
2021-05-28 06:48:57,691 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 06:48:58,458 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 4032
}

2021-05-28 06:48:58,858 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1132
  total_bytes: 4229
}

2021-05-28 06:48:58,960 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3793
  total_bytes: 4229
}

2021-05-28 06:48:59,061 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4229
  total_bytes: 4229
}

2021-05-28 06:48:59,163 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4229
  total_bytes: 4229
}

2021-05-28 06:48:59,264 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4229
  total_bytes: 4229
}

2021-05-28 06:48:59,366 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4229
  total_bytes: 4229
}

2021-05-28 06:48:59,467 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4229
  total_bytes: 4229
}

2021-05-28 06:48:59,569 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4229
  total_bytes: 4229
}

2021-05-28 06:48:59,670 INFO    MainThread:29752 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4229
  total_bytes: 4229
}

2021-05-28 06:49:00,757 INFO    MainThread:29752 [wandb_run.py:_show_summary():1812] rendering summary
2021-05-28 06:49:00,759 INFO    MainThread:29752 [wandb_run.py:_show_history():1850] rendering history
2021-05-28 06:49:00,760 INFO    MainThread:29752 [wandb_run.py:_show_files():1879] logging synced files
2021-05-28 06:49:00,762 INFO    MainThread:29752 [wandb_init.py:init():418] starting backend
2021-05-28 06:49:00,762 INFO    MainThread:29752 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 06:49:00,765 INFO    MainThread:29752 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 06:49:00,813 INFO    MainThread:29752 [backend.py:ensure_launched():136] started backend process with pid: 32186
2021-05-28 06:49:00,815 INFO    MainThread:29752 [wandb_init.py:init():423] backend started and connected
2021-05-28 06:49:00,817 INFO    MainThread:29752 [wandb_init.py:init():465] updated telemetry
2021-05-28 06:49:00,817 INFO    MainThread:29752 [wandb_init.py:init():484] communicating current version
2021-05-28 06:49:01,661 INFO    MainThread:29752 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 06:49:01,661 INFO    MainThread:29752 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 06:49:01,881 INFO    MainThread:29752 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 06:49:01,923 INFO    MainThread:29752 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 06:49:01,924 INFO    MainThread:29752 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 06:49:01,924 INFO    MainThread:29752 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 06:49:01,925 INFO    MainThread:29752 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 06:49:01,925 INFO    MainThread:29752 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 06:59:57,065 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 06:59:57,065 INFO    MainThread:29752 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 06:59:57,065 INFO    MainThread:29752 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_065957-1k5ivj83/logs/debug.log
2021-05-28 06:59:57,065 INFO    MainThread:29752 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_065957-1k5ivj83/logs/debug-internal.log
2021-05-28 06:59:57,065 INFO    MainThread:29752 [wandb_init.py:init():369] calling init triggers
2021-05-28 06:59:57,065 INFO    MainThread:29752 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 160, 'batch_size': 64, 'init_lr': 0.0001068764127678761}
2021-05-28 06:59:57,065 INFO    MainThread:29752 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 2iv7ryy0
2021-05-28 06:59:57,065 INFO    MainThread:29752 [wandb_run.py:finish():1208] finishing run seokjin/optuna/2iv7ryy0
