2021-05-27 23:19:11,528 INFO    MainThread:22131 [wandb_setup.py:_flush():69] setting env: {}
2021-05-27 23:19:11,528 INFO    MainThread:22131 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-27 23:19:11,528 INFO    MainThread:22131 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210527_231911-2r0tz9qr/logs/debug.log
2021-05-27 23:19:11,528 INFO    MainThread:22131 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210527_231911-2r0tz9qr/logs/debug-internal.log
2021-05-27 23:19:11,528 INFO    MainThread:22131 [wandb_init.py:init():369] calling init triggers
2021-05-27 23:19:11,529 INFO    MainThread:22131 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 2, 'batch_size': 64, 'init_lr': 0.0003292559050945966}
2021-05-27 23:19:11,529 INFO    MainThread:22131 [wandb_init.py:init():418] starting backend
2021-05-27 23:19:11,529 INFO    MainThread:22131 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-27 23:19:11,536 INFO    MainThread:22131 [backend.py:ensure_launched():132] starting backend process...
2021-05-27 23:19:11,541 INFO    MainThread:22131 [backend.py:ensure_launched():136] started backend process with pid: 22140
2021-05-27 23:19:11,542 INFO    MainThread:22131 [wandb_init.py:init():423] backend started and connected
2021-05-27 23:19:11,543 INFO    MainThread:22131 [wandb_init.py:init():465] updated telemetry
2021-05-27 23:19:11,544 INFO    MainThread:22131 [wandb_init.py:init():484] communicating current version
2021-05-27 23:19:12,342 INFO    MainThread:22131 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-27 23:19:12,342 INFO    MainThread:22131 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-27 23:19:13,323 INFO    MainThread:22131 [wandb_init.py:init():522] starting run threads in backend
2021-05-27 23:19:13,371 INFO    MainThread:22131 [wandb_run.py:_console_start():1565] atexit reg
2021-05-27 23:19:13,371 INFO    MainThread:22131 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-27 23:19:13,371 INFO    MainThread:22131 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-27 23:19:13,373 INFO    MainThread:22131 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-27 23:19:13,373 INFO    MainThread:22131 [wandb_init.py:init():546] run started, returning control to user process
2021-05-27 23:19:13,380 INFO    MainThread:22131 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-27 23:19:13,383 INFO    MainThread:22131 [wandb_run.py:_restore():1507] restore
2021-05-27 23:19:15,391 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-27 23:19:15,674 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-27 23:19:16,342 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3857
}

2021-05-27 23:19:16,725 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3794
  total_bytes: 3859
}

2021-05-27 23:19:16,827 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3794
  total_bytes: 3859
}

2021-05-27 23:19:16,929 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3859
  total_bytes: 3859
}

2021-05-27 23:19:17,030 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3859
  total_bytes: 3859
}

2021-05-27 23:19:17,132 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3859
  total_bytes: 3859
}

2021-05-27 23:19:17,234 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3859
  total_bytes: 3859
}

2021-05-27 23:19:17,336 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3859
  total_bytes: 3859
}

2021-05-27 23:19:17,438 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3859
  total_bytes: 3859
}

2021-05-27 23:19:17,540 INFO    MainThread:22131 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3859
  total_bytes: 3859
}

2021-05-27 23:19:18,630 INFO    MainThread:22131 [wandb_run.py:_show_files():1879] logging synced files
