2021-05-28 04:39:45,809 INFO    MainThread:29705 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 04:39:45,809 INFO    MainThread:29705 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 04:39:45,809 INFO    MainThread:29705 [wandb_init.py:_log_setup():336] Logging user logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_043945-3ne6adma/logs/debug.log
2021-05-28 04:39:45,810 INFO    MainThread:29705 [wandb_init.py:_log_setup():337] Logging internal logs to /opt/ml/gitclone/p4-mod-model_diet/wandb/run-20210528_043945-3ne6adma/logs/debug-internal.log
2021-05-28 04:39:45,810 INFO    MainThread:29705 [wandb_init.py:init():369] calling init triggers
2021-05-28 04:39:45,810 INFO    MainThread:29705 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'img_size': 224.0, 'batch_size': 8, 'init_lr': 0.00738039196472568}
2021-05-28 04:39:45,810 INFO    MainThread:29705 [wandb_init.py:init():418] starting backend
2021-05-28 04:39:45,810 INFO    MainThread:29705 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 04:39:45,819 INFO    MainThread:29705 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 04:39:45,826 INFO    MainThread:29705 [backend.py:ensure_launched():136] started backend process with pid: 29714
2021-05-28 04:39:45,827 INFO    MainThread:29705 [wandb_init.py:init():423] backend started and connected
2021-05-28 04:39:45,828 INFO    MainThread:29705 [wandb_init.py:init():465] updated telemetry
2021-05-28 04:39:45,829 INFO    MainThread:29705 [wandb_init.py:init():484] communicating current version
2021-05-28 04:39:46,571 INFO    MainThread:29705 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 04:39:46,571 INFO    MainThread:29705 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 04:39:46,794 INFO    MainThread:29705 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 04:39:46,829 INFO    MainThread:29705 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 04:39:46,830 INFO    MainThread:29705 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 04:39:46,830 INFO    MainThread:29705 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 04:39:46,832 INFO    MainThread:29705 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 04:39:46,832 INFO    MainThread:29705 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 04:39:49,815 INFO    MainThread:29705 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-28 04:39:49,818 INFO    MainThread:29705 [wandb_run.py:_restore():1507] restore
2021-05-28 04:39:51,825 INFO    MainThread:29705 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:39:52,049 INFO    MainThread:29705 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2021-05-28 04:39:52,821 INFO    MainThread:29705 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 3896
}

2021-05-28 04:39:53,209 INFO    MainThread:29705 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3898
  total_bytes: 3898
}

2021-05-28 04:39:53,311 INFO    MainThread:29705 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3898
  total_bytes: 3898
}

2021-05-28 04:39:53,412 INFO    MainThread:29705 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3898
  total_bytes: 3898
}

2021-05-28 04:39:53,514 INFO    MainThread:29705 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3898
  total_bytes: 3898
}

2021-05-28 04:39:53,616 INFO    MainThread:29705 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3898
  total_bytes: 3898
}

2021-05-28 04:39:53,718 INFO    MainThread:29705 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3898
  total_bytes: 3898
}

2021-05-28 04:39:54,806 INFO    MainThread:29705 [wandb_run.py:_show_files():1879] logging synced files
